### ISSUE TITLE
read packet from back-end (all)

### ISSUE THREAD

**Issue by Phillipnewell** [cs481-ekh/f22-gneiss#178]
As a user, I want to get all packets, so that I can decide which one to take a closer look at

## Definition of Done
- [x] All packets which exist in redis get their name/id returned in a http response
- [x] Tests are created and passing, testing manually in postman works

## Tasks
- [x] #195
- [x] #196
- [x] #197

**Comment by TheodoreRamey** [comment]
Spent 2.25 hours pair programming with Phillip working on this story. We created a getAllKeys function to get packet id's from redis and tested it via postman. We ran into a blocker over how to deal with keys/fields we're getting back from Redis and are going to have a meeting on it with other people from the group tomorrow.

**Comment by TheodoreRamey** [comment]
Spent 2 hours working on get all packets. I wasn't able to work on this through the week after my pair programming session as I had jury duty taking up a lot of my time. I implemented two methods in the packetDAO to get all packets ID's for a specific user and all of them no matter the user. I also added a way to get the jwt from the auth header in order to get the user and their role to correctly call get all packets or get all for a specific user. I started testing this via postman and ran into a bug in the parseJWT method which means my functions can't correctly get the user/role from the auth header.

**Comment by TheodoreRamey** [comment]
Spent ~1 hour looking into the bug with parseJWT and found the root of the problem. We have two rest controllers using different instances of our JWT class, so the signing key is different. I will have to use dependency injection via spring boot to solve the issue which I will have to research how to do.

**Comment by TheodoreRamey** [comment]
Spent 2.5 hours working on dependency injection. Researched DI in spring boot/kotlin and tried a few different avenues. Got a build together that compiles but fails all the tests due to ApplicationContext failing to load/ being unable to create beans without errors. I tried to fix this by mocking the bean in the tests with mockkbean annotations but that didn't fix anything. Need to take a break after bashing my head against the wall for the past hour of work/testing and not finding anything helpful online.

**Comment by TheodoreRamey** [comment]
Unable to finish during sprint 3 due to issues implementing DI in Spring Boot.

**Comment by TheodoreRamey** [comment]
Spent 3 hours finishing up the implementation of DI via Spring Boot. Got all tests running and figured out the issues I was having with DI. I wasn't properly injecting stuff into the restControllers constructors, instead I was trying to inject it as a field. All tests are running properly and the endpoint works correctly through postman.

**Comment by TheodoreRamey** [comment]
Spent 2 hours fixing issues pointed out with my PR, updating return values, response classes, and started doing research on how to properly convert the redis return hash into a POJO so I can return a set of packets instead of just their ID's.

**Comment by TheodoreRamey** [comment]
Spent 1 hour adding the ability to the getAllPackets endpoint to return all packets as JSON inside the response body. Fixed issues I had with docker where the docker image wasn't being updated correctly so I couldn't test my updated code. Passed unit tests and tested manually in postman.
